server:
  port: 8081
  servlet:
    context-path: /luckymoney

minMoney: 1
description: 最少发${minMoney}元

limit:
  minMoney: 1
  maxMoney: 999
  description: 最少发${limit.minMoney}，最多发${limit.maxMoney}

#配置datesource以及jpa
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?characterEncoding=utf-8
    username: root
    password: 8023hyx1999hyx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true