package com.fehead.dao;

import com.fehead.dataobject.ItemStock;
import org.apache.ibatis.annotations.Param;

public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int insertSelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    ItemStock selectByPrimaryKey(Integer id);

    //通过item_id查询stock信息
    ItemStock selectByItemId(Integer item_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int updateByPrimaryKey(ItemStock record);

    //减库存操作
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}