package com.fehead.dao;

import com.fehead.dataobject.ItemInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int insert(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int insertSelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    ItemInfo selectByPrimaryKey(Integer id);

    //查询所有数据列表
    List<ItemInfo> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int updateByPrimaryKeySelective(ItemInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat May 11 11:16:11 CST 2019
     */
    int updateByPrimaryKey(ItemInfo record);

    //增加销量
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}